name: GitHub Actions Java CI with Maven

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'openjdk'
        cache: maven

    - name: Build with Maven
      run: mvn clean package
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Run tests
      run: mvn test

    - name: Checkstyle
      run: mvn checkstyle:check

    - name: PMD
      run: mvn pmd:pmd

    - name: Spotbugs
      run: mvn spotbugs:check

    - name: Generate JaCoCo report
      run: mvn jacoco:report

    - name: Upload JaCoCo report
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: target/site/jacoco/
